[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[mounts]]
source = "railway_volume"
destination = "/app/data"